spring.application.name=identityAndUser-service
# Run on a random available port in Docker, or specific port locally
server.port=8081

# --- DATABASE CONFIGURATION ---
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5435}/${DB_NAME:agro_link_db}
spring.datasource.username=${DB_USER:agro_admin}
spring.datasource.password=${DB_PASSWORD:secure_agro_password_123}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=identity_schema

# --- EUREKA CONFIGURATION ---
eureka.client.serviceUrl.defaultZone=http://${EUREKA_HOST:localhost}:8761/eureka/
eureka.instance.prefer-ip-address=true
spring.cloud.config.enabled=false

# JWT Configuration
application.security.jwt.secret-key=${JWT_SECRET}
application.security.jwt.expiration=86400000

# Email configuration
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
