# tell Spring to import config from the config server
# application.properties (client)
#spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.enabled=false

# Force Eureka to use IP Address (127.0.0.1) instead of Hostname
eureka.instance.prefer-ip-address=true
# 1. Service Name (Must match what you call in the Gateway)
spring.application.name=orderPayment-service

# 2. Port (Run on 8082 to avoid conflict with Identity:8081 and Gateway:8080)
server.port=8075

# 3. Database Config
spring.datasource.url=jdbc:postgresql://localhost:5435/agro_link_db
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 4. Eureka Client Config (So it can be found)
eureka.client.service-url.defaultZone=http://${EUREKA_HOST:localhost}:8761/eureka/

#stripe
stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.public.key=${STRIPE_PUBLIC_KEY}
STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
stripe.price.id=${STRIPE_PRICE_ID}

# URL of your Frontend (Next.js)
client.base.url=http://localhost:3000