# tell Spring to import config from the config server
# application.properties (client)
#spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.enabled=false

# Force Eureka to use IP Address (127.0.0.1) instead of Hostname (RCN.mshome.net)
eureka.instance.prefer-ip-address=true
# 1. Service Name (Must match what you call in the Gateway)
spring.application.name=orderPayment-service

# 2. Port (Run on 8075)
server.port=8075

# 3. Database Config
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5435}/${DB_NAME:agro_link_db}
spring.datasource.username=${DB_USER:agro_admin}
spring.datasource.password=${DB_PASSWORD:secure_agro_password_123}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=order_schema

# 4. Eureka Client Config (So it can be found)
eureka.client.service-url.defaultZone=http://${EUREKA_HOST:localhost}:8761/eureka/

#stripe
stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.public.key=${STRIPE_PUBLIC_KEY}
STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
stripe.price.id=${STRIPE_PRICE_ID}

# URL of your Frontend (Next.js)
client.base.url=${CLIENT_BASE_URL:http://localhost:3000}
